server:
  port: 8080
  servlet:
    context-path: /wechat-share
spring:
#  jackson:
#    default-property-inclusion: non_null #返回数据为空不显示
  profiles:
    active: prod
mybatis-plus:
  type-aliases-package: com.eim.entity
logging:
  level:
    root:
    com.eim: debug